import Head from "next/head";

import AboutRoomSection from "@/components/AboutRoomSection";

import doubleRoomImages from "data/hotelData/doubleRoomImages.json";
import { doubleRoomTextInfo } from "data/hotelData/doubleRoomTextInfo";

export default function Hotel() {
  return (
    <>
      <Head>
        <title>MIMINO || Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-[#F6F6F6]">
        <AboutRoomSection
          // side
          data={doubleRoomImages}
          textInfo={doubleRoomTextInfo}
        />
      </div>
    </>
  );
}
