import Head from "next/head";

import AboutRoomSection from "@/components/AboutRoomSection";

import doubleRoomImages from "data/hotelData/doubleRoomImages.json";
import { doubleRoomTextInfo } from "data/hotelData/doubleRoomTextInfo";

import tripleRoomImages from "data/hotelData/tripleRoomImages.json";
import { tripleRoomTextInfo } from "data/hotelData/tripleRoomTextInfo";

import hotelFourSeaterRoom from "data/hotelData/hotelFourSeaterRoom.json";
import { hotelFourSeaterRoomTextInfo } from "data/hotelData/hotelFourSeaterRoomTextInfo";

export default function Hotel() {
  return (
    <>
      <Head>
        <title>MIMINO || Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-[#F6F6F6]">
        <AboutRoomSection
          data={doubleRoomImages}
          textInfo={doubleRoomTextInfo}
        />
        <AboutRoomSection
          side
          data={tripleRoomImages}
          textInfo={tripleRoomTextInfo}
        />
        <AboutRoomSection
          data={hotelFourSeaterRoom}
          textInfo={hotelFourSeaterRoomTextInfo}
        />
      </div>
    </>
  );
}
