import Head from "next/head";
import { Toaster } from "react-hot-toast";

import Hero from "@/components/Hero/Hero";
import RestaurantHotelComplex from "@/components/RestaurantHotelComplex";
import BusinessClassHotel from "@/components/BusinessClassHotel";
import AboutLuxary from "@/components/AboutLuxary";
import HotelDetails from "@/components/HotelDetails";
import RestaurantDetails from "@/components/RestaurantDetails/RestaurantDetails";

export default function Home() {
  return (
    <>
      <Head>
        <title>MIMINO || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <RestaurantHotelComplex />
      <BusinessClassHotel />
      <RestaurantDetails />
      <AboutLuxary />
      <HotelDetails />
      <Toaster />
    </>
  );
}
