import Head from "next/head";

import AboutServices from "@/components/AboutServices";
import AboutRoom from "@/components/AboutRoom";

import roomSliderImages from "data/roomData/roomSliderImages.json";

import generalAmenities from "data/roomData/generalAmenities.json";
import bathroom from "data/roomData/bathroom.json";
import bedroom from "data/roomData/bedroom.json";
import kitchen from "data/roomData/kitchen.json";
import media from "data/roomData/media.json";

const aboutRoomData = [generalAmenities, bathroom, bedroom, kitchen, media];

const Room = () => {
  return (
    <>
      <Head>
        <title>MIMINO || Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-[#F6F6F6]">
        <AboutServices title="DOUBLE LUXURY ROOM" images={roomSliderImages} />
      </div>
      <AboutRoom data={aboutRoomData} />
    </>
  );
};

export default Room;
